---
# tasks file for configuring firewall on RedHat, CentOS, Fedora

  - name: Open Redis Slave Port
    firewalld:
      port: "{{ slave_port }}/tcp"
      permanent: true
      state: enabled
    become: true
    become_method: sudo

  - name: Open SSH Port
    firewalld:
      port: 22/tcp
      permanent: true
      state: enabled
    become: true
    become_method: sudo
