---
# tasks file for configuring firewall on Ubuntu and Debian

  - name: Open Redis Slave Port
    ufw:
      rule: allow
      port: "{{ slave_port }}"
      proto: tcp
    become: true
    become_method: sudo

  - name: Open SSh Port
    ufw:
      rule: allow
      port: 22
      proto: tcp
    become: true
    become_method: sudo
